-- Add execution_spec column to analysis_selections table
-- This stores the direct execution specification generated by the frontend LLM,
-- allowing the backend to skip the decision service entirely.
ALTER TABLE public.analysis_selections
ADD COLUMN execution_spec jsonb;
